### ISSUE TITLE
unable to use FastMarkerCluster with anything more than lat/lng pairs in data

### ISSUE THREAD

**Issue by ramesesjd** [python-visualization/folium#1089]
Hello,

Firstly, thanks for all you work on folium; I'm quite new to Python but have some experience with GIS and am really very impressed at how sophisticated folium is.

I'm having some trouble adapting [this example (at In [6] and [7])](https://nbviewer.jupyter.org/gist/anonymous/33f38b09ad3bfa277e2d9c06e4bb588c) from @JamesGardiner to my situation. Some example code below to illustrate the problem I'm having.

```python
import pandas as pd
import numpy as np
import folium
import folium.plugins as plugins

lats = np.asarray([-54.4, -54.5, -54.6])
longs = np.asarray([-69.5, -69.5, -69.5])
data = np.asarray([70, 90, 5])
color = np.asarray(['green', 'orange', 'red'])

dummy = [list(a) for a in zip(lats, longs)]
d1map = folium.Map(location = [-54.5, -69.5], zoom_start = 7)
plugins.FastMarkerCluster(dummy).add_to(d1map)
d1map

dummy2 = pd.DataFrame(dummy, columns=['lat', 'lng'])
d2map = folium.Map(location = [-54.5, -69.5], zoom_start = 7)
plugins.FastMarkerCluster(dummy2).add_to(d2map)
d2map  ## this gives me 'TypeError: must be real number, not str'

dummy3 = [list(a) for a in zip(lats, longs, data, color)]
dummy3 = pd.DataFrame(dummy3, columns=['lat', 'lng', 'data', 'color'])
d3map = folium.Map(location = [-54.5, -69.5], zoom_start = 7)
plugins.FastMarkerCluster(dummy3).add_to(d3map)
d3map  ## this gives me 'TypeError: must be real number, not str'

```
#### Problem description
I can combine a list of lat and lng and pass that to FastMarkerCluster and plot the points/clusters. However, converting to a dataframe then to JSON, as in the example notebook above, gives me `TypeError: must be real number, not str`. Also, if I combine anything more with the lat and lng, and pass this to FastMarkerCluster, I get a blank map.  Converting to a dataframe then converting to JSON gives me the same error as above.

#### Expected Output
I'd like to produce a map with FastMarkerCluster using callbacks to display popups as in the linked example above, and ideally also show different symbol colours based on the data.  I am unable to give FastMarkerCluster anything more than lat/lng pairs, however, preventing me from using the remaining data in a callback.

FYI I can seemingly do this with no problems using MarkerCluster (see my example 1 in SO question [here](https://stackoverflow.com/questions/55082227/use-customized-markers-in-fastmarkercluster-in-python-folium)), but my data has several thousand rows so that would be infeasible.

#### Output of ``folium.__version__``
0.8.2

Many thanks in advance,
-Rameses

**Comment by Conengmo** [comment]
Hi Rameses,

This has something to do with the utilities we use to validate and convert coordinates. I cannot immediately figure out what the problem is, but it seems these functions are ripe for improvement. I'll whip up a PR that refactors them a bit and should solve your problem as well.

**Comment by Conengmo** [comment]
Seems the issue was that the header names of the Pandas dataframe were also parsed as if they were coordinates. That's why the error message said it's a 'str'. You can fix it by passing the (Numpy array) values instead of the dataframe: `df.values`. Even so, folium should either handle this case or raise a more meaningful error.

**Comment by Conengmo** [comment]
PR pending: #1090. (Note that this only solves the 'bug' in your `dummy2` example)

**Comment by Conengmo** [comment]
I worked on this a bit in #1090, but it may not solve your issue. The `FastMarkerCluster` class is quite flexible, so it is not that beginner friendly.

Convert your dataframe to a Numpy array or even a list and pass that to `FastMarkerCluster`:
`df.values.tolist()`

To use the data and color values you have to also pass a Javascript callback function.

**Comment by ramesesjd** [comment]
Hello @Conengmo,

Thanks for your prompt response and the information you provide.

Using your suggestion to convert to a Numpy array allows example dummy2 to work:
```
dummy2 = pd.DataFrame(dummy, columns=['lat', 'lng'])
dummy2 = dummy2.values  ## convert to Numpy array
d2map = folium.Map(location = [-54.5, -69.5], zoom_start = 7)
plugins.FastMarkerCluster(dummy2).add_to(d2map)
d2map  ## works!
```

However, I still get `TypeError: must be real number, not numpy.str_` in example dummy3, but I can get it to work if I remove the non-numeric fields (i.e. 'color').
```
dummy3 = [list(a) for a in zip(lats, longs, data, color)]
dummy3 = pd.DataFrame(dummy3, columns=['lat', 'lng', 'data', 'color'])
dummy3 = dummy3.values  ## convert to Numpy array
d3map = folium.Map(location = [-54.5, -69.5], zoom_start = 7)
plugins.FastMarkerCluster(dummy3).add_to(d3map)
d3map  ## this gives me 'TypeError: must be real number, not str'

dummy4 = [list(a) for a in zip(lats, longs, data)]
dummy4 = pd.DataFrame(dummy4, columns=['lat', 'lng', 'data'])
dummy4 = dummy4.values  ## convert to Numpy array
d4map = folium.Map(location = [-54.5, -69.5], zoom_start = 7)
plugins.FastMarkerCluster(dummy4).add_to(d4map)
d4map  ## works!
```
It appears that passing FastMarkerCluster *any* non-numeric data causes this hiccup.  This is apparently not the case in @JamesGardiner's [example (In [6])](https://nbviewer.jupyter.org/gist/anonymous/33f38b09ad3bfa277e2d9c06e4bb588c), where he makes a Pandas dataframe with lat, lng and names fields and uses a callback to display popups showing the content of the 'name' field.  Given the issue with parsing non-numeric data that I describe, I'm not sure how I'd make a callback that would read the appropriate 'color' for a data point in my examples.

Thanks again for your assistance.  Though my coding skills are presently not to par, I am happy to do anything I can do to help folium along (e.g. documentation).

Regards,
-R

**Comment by Conengmo** [comment]
You're right about the problems with the strings. That should be fixed in pending PR #1090.

**Comment by ramesesjd** [comment]
Ah, okay.  Thanks for fixing this, @Conengmo.

Should I close this issue, then?  Or wait till the PR is approved?

**Comment by Conengmo** [comment]
You can leave it open, it will get closed when we merge the PR.

**Comment by Conengmo** [comment]
PR was merged, so if you install from master things should be better!

**Comment by ramesesjd** [comment]
Hi @Conengmo,

Thank you again for your work on this.  I still can't seem to get the dummy examples I originally provided to work, but I get a different error message with d2map and d3map now: `RecursionError: maximum recursion depth exceeded in comparison`.

I installed folium again with `pip install --user --upgrade folium` and `print(folium.__version__)` shows 0.8.3.  I thought that `--upgrade` would give me the most up-to-date version of folium, but maybe I'm mistaken?  Sorry if my question is very basic at this point.

Regards,
-Rameses

**Comment by Conengmo** [comment]
You got the most recent release from the Pypi package repository, not the our git master branch. You can install it with something like ‘git install git+https://GitHub.com folium folium.git’ or something. The link is on the GitHub page.

**Comment by ramesesjd** [comment]
Thank you!
